<?php echo $header; ?>
<main class="index" role="main">
	<div class="container">
		<div class="pictures"></div>
		<h1>Álomotthon kalkulátor</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores magnam fugit esse sint labore architecto quis repellendus voluptas! Cupiditate fugit placeat natus quos sunt voluptas culpa officia quod sed nam.</p>
		<p class="bold">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam accusamus dicta ullam consequuntur sunt incidunt, asperiores, odio delectus! Error id nemo aspernatur atque natus et sunt quam dolore iusto voluptatem.</p>
		<a href="/lakastakarek/valasszon-lakasmeretet" class="btn-blue">Belépés</a>
	</div>
</main>
<?php echo $footer; ?>
