<?php echo $header; ?>
<main class="size">
	<div class="container">
		<ul class="navigation">
			<li><a class="active" href="#"><span>1</span></a></li>
			<li><a href="#"><span>2</span></a></li>
			<li><a href="#"><span>3</span></a></li>
			<li><a href="#"><span>4</span></a></li>
			<li><a href="#"><span>5</span></a></li>
		</ul>
		<h1>Válasszon lakásméretet!</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores magnam fugit esse sint labore architecto quis repellendus voluptas! Cupiditate fugit placeat natus quos sunt voluptas culpa officia quod sed nam.</p>
		<div class="sizes clear">
			<div class="small">
				<div class="bubble">30-45<span>m<sup>2</sup></span></div>
			</div>
			<div class="medium">
				<div class="bubble">45-65<span>m<sup>2</sup></span></div>
			</div>
			<div class="large">
				<div class="bubble">65+<span>m<sup>2</sup></span></div>
			</div>
		</div>
		<a href="/lakastakarek/helyiseg-valaszto" class="btn-blue">Tovább</a>
	</div>
</main>
<?php echo $footer; ?>
