<?php echo $header; ?>
<main class="area">
	<div class="container">
		<ul class="navigation">
			<li><a class="done" href="#"><span>1</span></a></li>
			<li><a class="active" href="#"><span>2</span></a></li>
			<li><a href="#"><span>3</span></a></li>
			<li><a href="#"><span>4</span></a></li>
			<li><a href="#"><span>5</span></a></li>
		</ul>
		<h1>Lakásom</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores magnam fugit esse sint labore architecto quis repellendus voluptas! Cupiditate fugit placeat natus quos sunt voluptas culpa officia quod sed nam.</p>
		<div class="add clear">
			<div class="left">
				<div class="room">
					<a href="#" class="close"></a>
					<h3>Konyha</h3>
					<div class="svg"></div>
					<footer>Terület: <span>13 m<sup>2</sup></span></footer>
				</div>
				<div class="room">
					<a href="#" class="close"></a>
					<h3>Konyha</h3>
					<div class="svg"></div>
					<footer>Terület: <span>13 m<sup>2</sup></span></footer>
				</div>
				<div class="room">
					<a href="#" class="close"></a>
					<h3>Konyha</h3>
					<div class="svg"></div>
					<footer>Terület: <span>13 m<sup>2</sup></span></footer>
				</div>
				<div class="room">
					<a href="#" class="close"></a>
					<h3>Konyha</h3>
					<div class="svg"></div>
					<footer>Terület: <span>13 m<sup>2</sup></span></footer>
				</div>
			</div>
			<div class="add-room">
				<h2>Helyiség hozzáadása</h2>
				<div class="tabs clear">
					<a href="#">Nappali</a>
					<a href="#">Fürdő</a>
					<a href="#">Konyha</a>
					<a href="#">Háló</a>
				</div>
				<label for="room-size" class="room-size">
					<input id="room-size" type="text">
					<span>m<sup>2</sup></span>
				</label>
			</div>
		</div>
		<div class="buttons">
			<a href="/lakastakarek/valasszon-lakasmeretet" class="btn-ghost">Vissza</a>
			<a href="/lakastakarek/valasszon" class="btn-blue">Tovább</a>
		</div>
	</div>
</main>
<?php echo $footer; ?>
