<?php echo $header; ?>
<main class="calc" role="main">
<div class="container">
	<ul class="navigation">
		<li><a class="done" href="#"><span>1</span></a></li>
		<li><a class="done" href="#"><span>2</span></a></li>
		<li><a class="done" href="#"><span>3</span></a></li>
		<li><a class="active" href="#"><span>4</span></a></li>
		<li><a href="#"><span>5</span></a></li>
	</ul>
	<div class="wrapper">
		<h1>Kalkuláció</h1>
		<div class="size">Lakásméret: <span>45-65 m<sup>2</sup></span><div class="room">Helyiség: <span>Konyha</span></div></div>
	</div>
</div>
</main>
<?php echo $footer; ?>