<?php echo $header; ?>
<main class="choose" role="main">
<div class="container">
	<ul class="navigation">
		<li><a class="done" href="#"><span>1</span></a></li>
		<li><a class="done" href="#"><span>2</span></a></li>
		<li><a class="active" href="#"><span>3</span></a></li>
		<li><a href="#"><span>4</span></a></li>
		<li><a href="#"><span>5</span></a></li>
	</ul>
	<h1>Válasszon</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores magnam fugit esse sint labore architecto quis repellendus voluptas! Cupiditate fugit placeat natus quos sunt voluptas culpa officia quod sed nam.</p>
</div>
<div class="wrapper">
	<div class="container">
		<div class="selected-size">Lakásméret: <span>45-65 m<sup>2</sup></span> Helyiség: <span>Konyha</span></div>
		<div class="left">
			<div class="price">
				<div class="planned">Tervezett ár:<span>2 450 000 Ft</span></div>
				<div class="real">Állami támogatás:<span>1 230 000 Ft</span></div>
			</div>
			<div class="svg"></div>
		</div>
		<div class="right">
			<div class="tab-nav">
				<a data-id="1" href="#">Helyiség</a>
				<a data-id="2" href="#">Berendezések</a>
				<a data-id="3" href="#">Gépek</a>
			</div>
			<div class="box"></div>
			<div class="buttons">
				<a class="btn-ghost" href="#">Mentés</a>
				<a class="btn-ghost" href="#">Új helyiség</a>
				<a class="btn-blue" href="#">Kész</a>
			</div>
		</div>
	</div>
</div>
</main>
<?php echo $footer; ?>